# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 656c9c8d8eca64154557f64b5ea157ee6238a648f9ee2a8f056b03664cb7e935adcc9cc183a52605f985c0148dc5b5d02d0fac0a1f48da547f02b2fac8801dae

test:
  secret_key_base: 90a2f58177b41587b239d9182bdf81f93bceb7d71abc06b429fd953a0cf5cb47728984561552bf3478172db7e637e78409762f1eae7c432a06eb969ba1b68174

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
